<?php

namespace Oni\CoreBundle\Entity\Repository;

use Doctrine\ORM\Query\Expr;
use Oni\CoreBundle\Doctrine\Spec\Specification;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{

	public function __construct(
		\Doctrine\ORM\EntityManager $em,
		\Doctrine\ORM\Mapping\ClassMetadata $class
	) {
		parent::__construct( $em, $class );

	}

	public function match(Specification $specification)
	{
		if ( ! $specification->supports($this->getEntityName())) {
			throw new \InvalidArgumentException("Specification not supported by this repository.");
		}

		$qb = $this->createQueryBuilder('c');
		$expr = $specification->match($qb, 'c');

		$query = $qb->where($expr)->getQuery();

		$specification->modifyQuery($query);

		return $query->getResult();
	}

}
