<?php

namespace Oni\CoreBundle\Entity\Repository;

use Oni\CoreBundle\Doctrine\Spec\Specification;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{

	public function match(Specification $specification)
	{
		if ( ! $specification->supports($this->getEntityName())) {
			throw new \InvalidArgumentException("Specification not supported by this repository.");
		}

		$qb = $this->createQueryBuilder('c');
		$expr = $specification->match($qb, 'c');

		$query = $qb->where($expr)->getQuery();

		$specification->modifyQuery($query);

		return $query->getResult();
	}

}
