<?php

namespace Oni\CoreBundle\Entity\Repository;

/**
 * NationalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalityRepository extends \Doctrine\ORM\EntityRepository
{
}
