oni_core_request:
    path:     /core/request
    defaults: { _controller: oni_general_service_controller:requestAction }

countries:
    type: rest
    resource: Oni\CoreBundle\Controller\Api\CountryController
